### ISSUE TITLE
Does client credentials not supply a refresh token?

### ISSUE THREAD

**Issue by jeff-winn** [jeff-winn/homebridge-automower-platform#216]
**Describe Your Problem:**
While reviewing the Authentication API documentation I noticed that Husqvarna will no longer be sending refresh tokens when using client credentials.

According to the OAuthToken definition in the code, it is currently expecting the value. Could cause a bug to pop once a day when the token expires, trying to use a non-existent refresh token.

Just need to verify the code behavior and make sure this scenario is correctly handled.

**Logs:**

```
[11/23/2022, 9:56:27 PM] [Homebridge Automower Platform] Refreshing the current token...
[11/23/2022, 9:56:27 PM] [Homebridge Automower Platform] Sending request [1/5]: 1e4db90a-bace-4d4b-aedb-84cfddce23c7
 {"url":"https://api.authentication.husqvarnagroup.dev/v1/oauth2/token","method":"POST","headers":{"content-type":["application/x-www-form-urlencoded;charset=UTF-8"],"x-application-id":["homebridge-automower-platform"]},"body":"client_id=REDACTED&grant_type=refresh_token&refresh_token=undefined"}
[11/23/2022, 9:56:27 PM] [Homebridge Automower Platform] Disconnected!
[11/23/2022, 9:56:28 PM] [Homebridge Automower Platform] Received response: 1e4db90a-bace-4d4b-aedb-84cfddce23c7
 {"status":400,"statusText":"Bad Request","headers":{"access-control-allow-headers":["Origin,X-Requested-With,X-Internal-Request-Id,X-External-Request-Id,Content-Type,Accept,X-IAM-Session,Authorization,Authorization-Provider"],"access-control-allow-methods":["GET, POST, OPTIONS, PUT, PATCH, DELETE"],"access-control-allow-origin":["*"],"cache-control":["no-store, no-cache, must-revalidate, proxy-revalidate"],"connection":["close"],"content-length":["136"],"content-type":["application/json; charset=utf-8"],"date":["Thu, 24 Nov 2022 02:56:27 GMT"],"etag":["W/\"88-ls5lEWqgHUCdISUBOBL/UeMMAXM\""],"expect-ct":["max-age=0"],"expires":["0"],"pragma":["no-cache"],"referrer-policy":["no-referrer"],"strict-transport-security":["max-age=15552000; includeSubDomains"],"surrogate-control":["no-store"],"via":["1.1 aa83353605ab84622a0546d65b02fbfc.cloudfront.net (CloudFront)"],"x-amz-apigw-id":["cFeGZEdvjoEFqWw="],"x-amz-cf-id":["1UDrlGNlf9PeYYNLNPCjUlmaQ44VG7xT0hyY50wtKwFHqM82elFnMA=="],"x-amz-cf-pop":["ORD58-P3"],"x-amzn-remapped-connection":["keep-alive"],"x-amzn-remapped-content-length":["136"],"x-amzn-remapped-date":["Thu, 24 Nov 2022 02:56:27 GMT"],"x-amzn-requestid":["cfe283d9-a159-4526-8cff-2d0933d4a796"],"x-cache":["Error from cloudfront"],"x-content-type-options":["nosniff"],"x-dns-prefetch-control":["off"],"x-frame-options":["SAMEORIGIN"],"x-internal-request-id":["929998185"],"x-permitted-cross-domain-policies":["none"],"x-xss-protection":["0"]},"body":{"error":"invalid_grant","error_description":"Invalid grant: refresh token was issued to another client","error_code":"token.not.found"}}
[11/23/2022, 9:56:28 PM] [Homebridge Automower Platform] An unexpected error occurred while keeping the client stream alive. BadOAuthTokenError: The access token supplied was invalid.
    at DefaultErrorFactory.badOAuthTokenError (/homebridge/node_modules/homebridge-automower-platform/dist/errors/errorFactory.js:27:16)
    at AuthenticationClientImpl.throwIfBadToken (/homebridge/node_modules/homebridge-automower-platform/dist/clients/authenticationClient.js:114:37)
    at AuthenticationClientImpl.<anonymous> (/homebridge/node_modules/homebridge-automower-platform/dist/clients/authenticationClient.js:106:18)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-automower-platform/dist/clients/authenticationClient.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errorCode: 'ERR0002'
}
[11/23/2022, 9:57:28 PM] [Homebridge Automower Platform] Checking keep alive for the client stream...
[11/23/2022, 9:57:28 PM] [Homebridge Automower Platform] The stream somehow got disconnected; proceed with reconnect.
[11/23/2022, 9:57:28 PM] [Homebridge Automower Platform] Attempting to open a connection...
[11/23/2022, 9:57:28 PM] [Homebridge Automower Platform] Logging into the Husqvarna platform...

```

**Plugin Config:**

```json
{
    "name": "Homebridge Automower Platform",
    "lang": "en",
    "appKey": "REDACTED",
    "authentication_mode": "client_credentials",
    "application_secret": "REDACTED",
    "platform": "Homebridge Automower Platform"
}
```

**Environment:**

* **Plugin Version**: v1.3.1
* **Homebridge Version**: v1.5.1
* **Node.js Version**: v18.12.1
* **Operating System**: docker

**Comment by jeff-winn** [comment]
Confirmed, after using Postman, the call definitely does not contain the refresh token any longer.
```json
{
    "access_token": "REDACTED",
    "scope": "iam:read amc:api",
    "expires_in": 86399,
    "provider": "husqvarna",
    "user_id": "REDACTED",
    "token_type": "Bearer"
}
```
