### ISSUE TITLE
Issue with simultaneous logins

### ISSUE THREAD

**Issue by jeff-winn** [jeff-winn/homebridge-automower-platform#336]
**Describe The Bug:**

I saw an issue recently happen randomly that caused the plugin to logout and prevented the keep alive from logging in again. Not sure if it was related, but both instances seemed to happen near each other.

**To Reproduce:**

Not sure what's causing it.

**Expected behavior:**

The simultaneous login issue should not be a problem as I only have one instance of the plugin running on one homebridge instance.

**Logs:**

```
[7/7/2023, 9:24:11 PM] [Homebridge Automower Platform] Logging into the Husqvarna platform...
[7/7/2023, 9:24:11 PM] [Homebridge Automower Platform] Sending request [1/5]: 28ab6d5c-3fea-4bc6-bfb9-1c26080ae58b
{"url":"https://api.authentication.husqvarnagroup.dev/v1/oauth2/token","method":"POST","body":"grant_type=client_credentials&client_id=REDACTED&client_secret=REDACTED&scope=iam%3Aread%20amc%3Aapi"}
[7/7/2023, 9:24:11 PM] [Homebridge Automower Platform] Logging into the Husqvarna platform...
[7/7/2023, 9:24:11 PM] [Homebridge Automower Platform] Sending request [1/5]: cdbfb99a-cf8d-4975-9206-0aadf791f862 {"url":"https://api.authentication.husqvarnagroup.dev/v1/oauth2/token","method":"POST","body":"grant_type=client_credentials&client_id=REDACTED&client_secret=REDACTED&scope=iam%3Aread%20amc%3Aapi"}
[7/7/2023, 9:24:11 PM] [Homebridge Automower Platform] Received response: cdbfb99a-cf8d-4975-9206-0aadf791f862
 {"status":400,"statusText":"Bad Request","body":{"error":"invalid_request","error_description":"Simultaneous logins detected for client[id=REDACTED], user[id=REDACTED, email=REDACTED}]","error_code":"simultaneous.logins"}}
[7/7/2023, 9:24:11 PM] [Homebridge Automower Platform] An unexpected error occurred while attempting to set 'Schedule' for 'Dobby'. SimultaneousLoginError: The account for the credentials supplied appears to be logged in multiple times, please check your account with Husqvarna and try again. If this activity seems suspicious, you should renew your application secret on the Husqvarna website.
    at DefaultErrorFactory.simultaneousLoginError (/homebridge/node_modules/homebridge-automower-platform/dist/errors/errorFactory.js:34:16)
    at AuthenticationClientImpl.<anonymous> (/homebridge/node_modules/homebridge-automower-platform/dist/clients/authenticationClient.js:83:45)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-automower-platform/dist/clients/authenticationClient.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errorCode: 'CFG0002'
}
```

**Plugin Config:**

```json
{
    "name": "Homebridge Automower Platform",
    "lang": "en",
    "appKey": "REDACTED",
    "authentication_mode": "client_credentials",
    "application_secret": "REDACTED",
    "platform": "Homebridge Automower Platform"
}
```

**Screenshots:**

**Mower:**

* **Year**: 2020
* **Model**: Automower 430XH

**Environment:**

* **Plugin Version**: v2.0.0-rc2
* **Homebridge Version**: v1.6.1
* **Node.js Version**: v18.13.0
* **Operating System**: Docker

**Comment by jeff-winn** [comment]
This could be due to the reliability issues from Sonar that were being addressed and changed the way that the async code is being interacted with on the login causing multiple executions to occur.

**Comment by jeff-winn** [comment]
I have not seen this occur within the past year
