### ISSUE TITLE
Unable to refresh token and failing to login again when token invalid

### ISSUE THREAD

**Issue by jeff-winn** [jeff-winn/homebridge-automower-platform#96]
The following errors were seen on the server while running this evening. It appears there is an issue with refreshing the token.

Expected Behavior:
- The token gets invalidated
- The authentication client gets a completely new token and throws out the old token
- The new token is used for subsequent calls to the APIs

Actual Behavior:
- The token gets invalidated
- The authentication client tries to refresh the old token
- The refresh fails, and the token is not completely thrown out
- The authentication client repeatedly tries to refresh the old token

See the following for a sample of the logs:
```
[6/23/2022, 6:00:10 PM] [Homebridge Automower Platform] Checking keep alive for the client stream...
[6/23/2022, 6:00:10 PM] [Homebridge Automower Platform] The stream somehow got disconnected; proceed with reconnect.
[6/23/2022, 6:00:10 PM] [Homebridge Automower Platform] Attempting to open a connection...
[6/23/2022, 6:00:10 PM] [Homebridge Automower Platform] Sending request [1/5]: 8b431637-1810-4f57-873c-2db1bd6bc1a9
 {"url":"https://api.authentication.husqvarnagroup.dev/v1/oauth2/token","method":"POST","headers":{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},"body":"client_id=__REDACTED__&grant_type=refresh_token&refresh_token=__REDACTED__"}
[6/23/2022, 6:00:10 PM] [Homebridge Automower Platform] Received response: 8b431637-1810-4f57-873c-2db1bd6bc1a9
 {"status":400,"statusText":"Bad Request","body":{"error":"invalid_grant","error_description":"Failed to find token","error_code":"token.not.found"}}
[6/23/2022, 6:00:10 PM] [Homebridge Automower Platform] An unexpected error occurred while keeping the client stream alive. BadOAuthTokenError: The access token supplied was invalid.
    at AuthenticationClientImpl.throwIfBadToken (/homebridge/node_modules/.pnpm/homebridge-automower-platform@1.0.0/node_modules/homebridge-automower-platform/dist/clients/authenticationClient.js:104:19)
    at AuthenticationClientImpl.<anonymous> (/homebridge/node_modules/.pnpm/homebridge-automower-platform@1.0.0/node_modules/homebridge-automower-platform/dist/clients/authenticationClient.js:96:18)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/.pnpm/homebridge-automower-platform@1.0.0/node_modules/homebridge-automower-platform/dist/clients/authenticationClient.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errorCode: 'ERR0002'
}
[6/23/2022, 6:01:10 PM] [Homebridge Automower Platform] Checking keep alive for the client stream...
[6/23/2022, 6:01:10 PM] [Homebridge Automower Platform] The stream somehow got disconnected; proceed with reconnect.
[6/23/2022, 6:01:10 PM] [Homebridge Automower Platform] Attempting to open a connection...
[6/23/2022, 6:01:10 PM] [Homebridge Automower Platform] Sending request [1/5]: 3b99e3af-9a01-4e8f-b133-7b514adfd9fa
 {"url":"https://api.authentication.husqvarnagroup.dev/v1/oauth2/token","method":"POST","headers":{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},"body":"client_id=__REDACTED__&grant_type=refresh_token&refresh_token=__REDACTED__"}
[6/23/2022, 6:01:11 PM] [Homebridge Automower Platform] Received response: 3b99e3af-9a01-4e8f-b133-7b514adfd9fa
 {"status":400,"statusText":"Bad Request","body":{"error":"invalid_request","error_description":"Too many login-attempts for this user, please try again later","error_code":"too.many.failed.login.attempts"}}
[6/23/2022, 6:01:11 PM] [Homebridge Automower Platform] An unexpected error occurred while keeping the client stream alive. BadOAuthTokenError: The access token supplied was invalid.
    at AuthenticationClientImpl.throwIfBadToken (/homebridge/node_modules/.pnpm/homebridge-automower-platform@1.0.0/node_modules/homebridge-automower-platform/dist/clients/authenticationClient.js:104:19)
    at AuthenticationClientImpl.<anonymous> (/homebridge/node_modules/.pnpm/homebridge-automower-platform@1.0.0/node_modules/homebridge-automower-platform/dist/clients/authenticationClient.js:96:18)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/.pnpm/homebridge-automower-platform@1.0.0/node_modules/homebridge-automower-platform/dist/clients/authenticationClient.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errorCode: 'ERR0002'
```

**Comment by jeff-winn** [comment]
Could be caused from the auth token manager not throwing out the token that was in use when flagged as invalid.

See the following snippet:
```
if (this.hasAlreadyLoggedIn()) {
    newToken = await this.doRefreshToken();
} else {
    newToken = await this.doLogin();
}
```
If the token that was in use is not valid, the first if block would attempt to use it.

**Comment by jeff-winn** [comment]
This causes the plug-in to fail reconnecting until Homebridge is restarted.
